// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WordMatch.API.Data;

#nullable disable

namespace WordMatch.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260822164248_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WordMatch.API.Features.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WordMatch.API.Features.Study.CurriculumTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Level", "SortOrder")
                        .IsUnique();

                    b.HasIndex("Level", "Topic")
                        .IsUnique();

                    b.ToTable("CurriculumTopics", null, t =>
                        {
                            t.HasCheckConstraint("CK_CurriculumTopics_Level", "\"Level\" IN ('A1', 'A2', 'B1', 'B2')");

                            t.HasCheckConstraint("CK_CurriculumTopics_SortOrder", "\"SortOrder\" > 0");

                            t.HasCheckConstraint("CK_CurriculumTopics_Status", "\"Status\" IN ('Active', 'Retired')");

                            t.HasCheckConstraint("CK_CurriculumTopics_Topic", "\"Topic\" IN ('Actions', 'Animals', 'ArtsAndEntertainment', 'BodyAndHealth', 'CalendarAndTime', 'Clothing', 'Colors', 'Countries', 'Days', 'Descriptions', 'Education', 'EmotionsAndPersonality', 'FamilyAndPeople', 'FoodAndDrink', 'General', 'HomeAndObjects', 'JobsAndWork', 'Months', 'NatureAndWeather', 'Numbers', 'Places', 'ShoppingAndMoney', 'SocietyAndPolitics', 'SportsAndLeisure', 'TechnologyAndMedia', 'Transportation', 'TravelAndHolidays')");
                        });
                });

            modelBuilder.Entity("WordMatch.API.Features.Study.CurriculumTopicWord", b =>
                {
                    b.Property<int>("CurriculumTopicId")
                        .HasColumnType("integer");

                    b.Property<int>("WordId")
                        .HasColumnType("integer");

                    b.Property<int>("LearningGroupSortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("CurriculumTopicId", "WordId");

                    b.HasIndex("WordId")
                        .IsUnique();

                    b.HasIndex("CurriculumTopicId", "LearningGroupSortOrder");

                    b.HasIndex("CurriculumTopicId", "SortOrder")
                        .IsUnique();

                    b.ToTable("CurriculumTopicWords", null, t =>
                        {
                            t.HasCheckConstraint("CK_CurriculumTopicWords_LearningGroupSortOrder", "\"LearningGroupSortOrder\" > 0");

                            t.HasCheckConstraint("CK_CurriculumTopicWords_SortOrder", "\"SortOrder\" > 0");
                        });
                });

            modelBuilder.Entity("WordMatch.API.Features.Study.StudySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ContinuationReservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurriculumTopicId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerDeviceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("ReturnToCurriculumTopicId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumTopicId");

                    b.HasIndex("ReturnToCurriculumTopicId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("UserId", "ContinuationReservedAtUtc")
                        .HasFilter("\"ContinuationReservedAtUtc\" IS NOT NULL");

                    b.ToTable("StudySessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_StudySessions_Mode", "\"Mode\" IN ('Topic', 'Review')");

                            t.HasCheckConstraint("CK_StudySessions_ModeSelection", "(\"Mode\" = 'Topic' AND \"CurriculumTopicId\" IS NOT NULL) OR (\"Mode\" = 'Review' AND \"CurriculumTopicId\" IS NULL)");

                            t.HasCheckConstraint("CK_StudySessions_Status", "\"Status\" IN ('Active', 'Completed', 'Abandoned')");
                        });
                });

            modelBuilder.Entity("WordMatch.API.Features.Study.StudySessionQuestion", b =>
                {
                    b.Property<Guid>("StudySessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("AcceptedAnswersSnapshot")
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset?>("AnsweredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrectAnswerSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CorrectIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnglishSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsIntroduction")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Options")
                        .HasColumnType("text[]");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<string>("PromptSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SelectedIndex")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedText")
                        .HasColumnType("text");

                    b.Property<int>("WordId")
                        .HasColumnType("integer");

                    b.HasKey("StudySessionId", "Position");

                    b.HasIndex("WordId");

                    b.HasIndex("StudySessionId", "WordId", "Dimension")
                        .IsUnique();

                    b.ToTable("StudySessionQuestions", null, t =>
                        {
                            t.HasCheckConstraint("CK_StudySessionQuestions_Answer", "(\"Outcome\" IS NULL AND \"SelectedIndex\" IS NULL AND \"SelectedText\" IS NULL AND \"AnsweredAtUtc\" IS NULL) OR (\"Outcome\" = 'Review' AND \"SelectedIndex\" IS NULL AND \"SelectedText\" IS NULL AND \"AnsweredAtUtc\" IS NOT NULL) OR (\"Kind\" = 'MultipleChoice' AND \"Outcome\" IN ('Correct', 'Wrong') AND \"SelectedIndex\" IS NOT NULL AND \"SelectedText\" IS NULL AND \"AnsweredAtUtc\" IS NOT NULL) OR (\"Kind\" = 'Written' AND \"Outcome\" IN ('Correct', 'Wrong') AND \"SelectedIndex\" IS NULL AND \"SelectedText\" IS NOT NULL AND length(trim(\"SelectedText\")) > 0 AND \"AnsweredAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_StudySessionQuestions_Dimension", "\"Dimension\" IN ('WrittenRecognition', 'WrittenRecall', 'AuralRecognition', 'SpokenRecall')");

                            t.HasCheckConstraint("CK_StudySessionQuestions_Kind", "\"Kind\" IN ('MultipleChoice', 'Written')");

                            t.HasCheckConstraint("CK_StudySessionQuestions_Position", "\"Position\" >= 0");

                            t.HasCheckConstraint("CK_StudySessionQuestions_QuestionData", "(\"Kind\" = 'MultipleChoice' AND \"Options\" IS NOT NULL AND cardinality(\"Options\") = 4 AND \"CorrectIndex\" IS NOT NULL AND \"CorrectIndex\" >= 0 AND \"CorrectIndex\" < 4 AND \"AcceptedAnswersSnapshot\" IS NULL) OR (\"Kind\" = 'Written' AND \"Options\" IS NULL AND \"CorrectIndex\" IS NULL AND \"AcceptedAnswersSnapshot\" IS NOT NULL AND cardinality(\"AcceptedAnswersSnapshot\") > 0)");
                        });
                });

            modelBuilder.Entity("WordMatch.API.Features.Study.UserStudySkillPause", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Dimension")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DeferredUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "Dimension");

                    b.HasIndex("DeferredUntilUtc");

                    b.ToTable("UserStudySkillPauses", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserStudySkillPauses_Dimension", "\"Dimension\" IN ('WrittenRecognition', 'WrittenRecall', 'AuralRecognition', 'SpokenRecall')");
                        });
                });

            modelBuilder.Entity("WordMatch.API.Features.Study.UserWordIntroduction", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("WordId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("IntroducedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "WordId");

                    b.HasIndex("WordId");

                    b.HasIndex("UserId", "IntroducedAtUtc");

                    b.ToTable("UserWordIntroductions", (string)null);
                });

            modelBuilder.Entity("WordMatch.API.Features.Study.UserWordMastery", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("WordId")
                        .HasColumnType("integer");

                    b.Property<string>("Dimension")
                        .HasColumnType("text");

                    b.Property<int>("ConsecutiveCorrectCount")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastOutcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastStudiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextReviewAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int>("WrongCount")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "WordId", "Dimension");

                    b.HasIndex("WordId");

                    b.HasIndex("UserId", "NextReviewAtUtc");

                    b.ToTable("UserWordMastery", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserWordMastery_Counts", "\"CorrectCount\" >= 0 AND \"ReviewCount\" >= 0 AND \"WrongCount\" >= 0 AND \"ConsecutiveCorrectCount\" >= 0");

                            t.HasCheckConstraint("CK_UserWordMastery_Dimension", "\"Dimension\" IN ('WrittenRecognition', 'WrittenRecall', 'AuralRecognition', 'SpokenRecall')");

                            t.HasCheckConstraint("CK_UserWordMastery_Outcome", "\"LastOutcome\" IN ('Correct', 'Review', 'Wrong')");

                            t.HasCheckConstraint("CK_UserWordMastery_Stage", "\"Stage\" >= 0 AND \"Stage\" <= 5");
                        });
                });

            modelBuilder.Entity("WordMatch.API.Features.Words.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImportKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsIrregular")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PastParticiple")
                        .HasColumnType("text");

                    b.Property<string>("PastSimple")
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("TurkishTranslations")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("ImportKey")
                        .IsUnique();

                    b.HasIndex("English", "PartOfSpeech")
                        .IsUnique();

                    b.ToTable("Words", null, t =>
                        {
                            t.HasCheckConstraint("CK_Words_ImportKey", "length(trim(\"ImportKey\")) > 0");

                            t.HasCheckConstraint("CK_Words_Level", "\"Level\" IN ('A1', 'A2', 'B1', 'B2')");

                            t.HasCheckConstraint("CK_Words_PartOfSpeech", "\"PartOfSpeech\" IN ('Verb', 'Noun', 'Adjective', 'ProperNoun', 'Number', 'Pronoun')");

                            t.HasCheckConstraint("CK_Words_Topic", "\"Topic\" IN ('Actions', 'Animals', 'ArtsAndEntertainment', 'BodyAndHealth', 'CalendarAndTime', 'Clothing', 'Colors', 'Countries', 'Days', 'Descriptions', 'Education', 'EmotionsAndPersonality', 'FamilyAndPeople', 'FoodAndDrink', 'General', 'HomeAndObjects', 'JobsAndWork', 'Months', 'NatureAndWeather', 'Numbers', 'Places', 'ShoppingAndMoney', 'SocietyAndPolitics', 'SportsAndLeisure', 'TechnologyAndMedia', 'Transportation', 'TravelAndHolidays')");

                            t.HasCheckConstraint("CK_Words_TurkishTranslations", "cardinality(\"TurkishTranslations\") > 0 AND array_position(\"TurkishTranslations\", NULL) IS NULL AND array_position(\"TurkishTranslations\", '') IS NULL");

                            t.HasCheckConstraint("CK_Words_VerbMetadata", "(\"PartOfSpeech\" = 'Verb' AND \"PastSimple\" IS NOT NULL AND \"PastParticiple\" IS NOT NULL) OR (\"PartOfSpeech\" <> 'Verb' AND \"PastSimple\" IS NULL AND \"PastParticiple\" IS NULL AND NOT \"IsIrregular\")");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WordMatch.API.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WordMatch.API.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordMatch.API.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WordMatch.API.Features.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WordMatch.API.Features.Study.CurriculumTopicWord", b =>
                {
                    b.HasOne("WordMatch.API.Features.Study.CurriculumTopic", "CurriculumTopic")
                        .WithMany("Words")
                        .HasForeignKey("CurriculumTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordMatch.API.Features.Words.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurriculumTopic");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("WordMatch.API.Features.Study.StudySession", b =>
                {
                    b.HasOne("WordMatch.API.Features.Study.CurriculumTopic", "CurriculumTopic")
                        .WithMany()
                        .HasForeignKey("CurriculumTopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordMatch.API.Features.Study.CurriculumTopic", "ReturnToCurriculumTopic")
                        .WithMany()
                        .HasForeignKey("ReturnToCurriculumTopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WordMatch.API.Features.Auth.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurriculumTopic");

                    b.Navigation("ReturnToCurriculumTopic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WordMatch.API.Features.Study.StudySessionQuestion", b =>
                {
                    b.HasOne("WordMatch.API.Features.Study.StudySession", "StudySession")
                        .WithMany("Questions")
                        .HasForeignKey("StudySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordMatch.API.Features.Words.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudySession");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("WordMatch.API.Features.Study.UserStudySkillPause", b =>
                {
                    b.HasOne("WordMatch.API.Features.Auth.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WordMatch.API.Features.Study.UserWordIntroduction", b =>
                {
                    b.HasOne("WordMatch.API.Features.Auth.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordMatch.API.Features.Words.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("WordMatch.API.Features.Study.UserWordMastery", b =>
                {
                    b.HasOne("WordMatch.API.Features.Auth.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WordMatch.API.Features.Words.Word", "Word")
                        .WithMany()
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("WordMatch.API.Features.Study.CurriculumTopic", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("WordMatch.API.Features.Study.StudySession", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
