// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WordMatch.API.Data;

#nullable disable

namespace WordMatch.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260719163226_EnrichWordMetadata")]
    partial class EnrichWordMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WordMatch.API.Features.Words.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("English")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsIrregular")
                        .HasColumnType("boolean");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PastParticiple")
                        .HasColumnType("text");

                    b.Property<string>("PastSimple")
                        .HasColumnType("text");

                    b.Property<string>("TurkishTranslation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Words", null, t =>
                        {
                            t.HasCheckConstraint("CK_Words_PartOfSpeech", "\"PartOfSpeech\" IN ('Verb', 'Noun', 'Adjective', 'ProperNoun')");

                            t.HasCheckConstraint("CK_Words_VerbMetadata", "(\"PartOfSpeech\" = 'Verb' AND \"PastSimple\" IS NOT NULL AND \"PastParticiple\" IS NOT NULL) OR (\"PartOfSpeech\" <> 'Verb' AND \"PastSimple\" IS NULL AND \"PastParticiple\" IS NULL AND NOT \"IsIrregular\")");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
